!cloudgene.mapred.util.Settings
apps: !java.util.Vector
-  id: vcf2circos@1.0.0
   changed: false
   filename: apps/vcf2circos/1.0.0/application.yaml
   permission: users
navigation: !java.util.Vector
- !cloudgene.mapred.util.MenuItem
   id: help
   name: Help
   link: https://github.com/lukfor/docker-cloudgene
secretKey: xvVSYZsOObhwfUwTMvrPLaRsLLcyMYXoshbxOclSXESHaxoDJwGWJktZJkaHUtwF
